src/Controller/ApiController.php
<?php

namespace App\Controller;

use App\Entity\ParsinId;
use App\Service\AdopteService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\EntityManagerInterface;
/**
 * @Route("/api")
 */
class ApiController extends AbstractController
{


    public function __construct(EntityManagerInterface $em, AdopteService $adopteService)
    {
        $this->em = $em;
        $this->adopteService = $adopteService;
    }

    /**
     * lat et lon definissent la position de l'utilisateur qui souhaite afficher les clients sur la carte
     * return une liste de client d'un perimetre de 8 kilometres en fonction de la position de l'utilisateur
     * @Route("/users/{lat}/{lon}", name="users")
     * @return Response
     */
    public function getClientsOnScreenLocate(Request $request, $lat, $lon)
    {
         $result = $this->em->getRepository('App:ParsingId')->getScreenLocateIds($lat,$lon); ///api/users/43.60436/1.44295 [toulouse]
         return new JsonResponse($result);
        
    }

    /**
     * return les coordonnées d'un client
     * @route("/user/locate/{id}", name="client_locate")
     * @return Response
     */
    public function getLatLonFromOneClient($id)
    {
       
        $results = $this->em->getRepository('App:ParsingId')->getId($id);

        // deserialize DC2Type to array
        foreach ($results as $result) {
            $data = unserialize($result["data"]);

            $tabResult[] = [
                'lat'        => $data['sideColumn']['map']["coords"]["memberLat"], // On le transforme en tableau
                'lon'        => $data['sideColumn']['map']["coords"]["memberLng"],
                'created'    => $result['created_at'] 
            ];

        }
       
        return new jsonResponse($tabResult);
    }


    /**
     * @Route("/similar/{id}", name="similar")
     */
    public function similar(Request $request, $id)
    {  
        $result = $this->adopteService->exctractAndCompareApi($id);
        return new jsonResponse($result);
    }


    /**
     * @Route("/search", name="Api_search")
     */
    public function apiSearch(Request $request)
    {  

        $result =  json_decode($request->request->get('data'),true);
        $chaine_de_recherche = $result["data"][0]["search"];
        $range = $result["data"][0]["range"];  
        $genre = $result["data"][0]["genre"]; 

       
        $mots = explode(" ", $chaine_de_recherche); // on sépare la chaine de recherche
        $mots[1] = isset($mots[1]) ? $mots[1] : '';
        $nombre_de_mot = count($mots); // la requette dependra du nombre de mot et construira la requette
        $result = $this->em->getRepository('App:ParsingId')->getSearch($mots, $range, $genre);

        return new jsonResponse($result);
    }

    /**
     * route privée qui active le worker app:parse
     * @Route("/user/worker/{etat}", name="play")
     */
    public function playWorker($etat)
    {
        if ($etat) {
                // activation du worker
        } else {
                //Desactivation du worker
        }

        return new JsonResponse();

    }

    /**
     *  @Route("/proxy", name="proxy")
     */
    public function proxy() {
        return new JsonResponse($this->adopteService->getProxy2());
    }


}

templates/layout/base.html.twig
<!DOCTYPE html>
<html>
    {{ include('layout/header.html.twig') }}
    <body style="padding-top:90px">
        {{ include('layout/navbar.html.twig') }}
        {% block body %}{% endblock %}
        {{ include('layout/footer.html.twig') }}
    </body>

</html>

templates/layout/footer.html.twig
{% if app.request.attributes.get('_route') matches '{admin}' == 0 %}
<footer class="pt-3 pb-5" style="background:#252525">
    <div class="container pt-4">
        <div class="row">
            <div class="col-12 col-md-2">
            Social Engine (web tools by @RbtsV2)
                <small class="d-block mb-3 text-muted">&copy; {{ date() | date('Y') }}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Support</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="">Contact us</a></li>
                    <li><a class="text-muted" href="">Help center</a></li>
                    <li><a class="text-muted" href="">FAQ</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="">Developers</a></li>
                    <li><a class="text-muted" href="">API Reference</a></li>
                    <li><a class="text-muted" href="">API Status</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="">Team</a></li>
                    <li><a class="text-muted" href="">Privacy</a></li>
                    <li><a class="text-muted" href="">Terms</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endif %}

{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>

 
{% if is_granted('ROLE_ADMIN') %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.full.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.6.7/jquery.timeago.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.6.7/locales/jquery.timeago.en.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.6.7/locales/jquery.timeago.fr.min.js"></script>
    

{% endif %}

{% if app.request.get('_route') == 'maps' %}
  
    <script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js"></script>
    <script src='{{ asset('assets/js/leaflet_fullscreen.js') }}'></script>
	<script src='{{ asset('assets/js/leafleft_map.js') }}'></script>
    <script src="https://leaflet.github.io/Leaflet.markercluster/dist/leaflet.markercluster-src.js"></script>
    <script>
        window.onload = function() {
            let leafletmap = new LeafleftMap({
            zoom: 12
            });
        };

    </script>
{% endif %}

{% if app.request.get('_route') == 'search' %}

    <script>

        var range = [18,35]; // range par default 
        var genre = [1, 0]; // On initialise le tableau de genre on initialise les deux avec => 1 = femme 0 = homme
        var champ = document.getElementById('search');
        // code concernant la route search à mettre dans un fichier js unique 
        var slider = new Slider("#slider1");
        slider.on("slide", function(slideEvt) {
            range = slider.getValue();
            actionSearch(champ);
        });
       
        $('#femme').click(function(){
            if($(this).prop("checked") == true){
                genre[0] = 1;
            }
            else if($(this).prop("checked") == false){
                genre[0] = null;
            }
            actionSearch(champ);
        });
        $('#homme').click(function(){
            if($(this).prop("checked") == true){
                genre[1] = 0;
            }
            else if($(this).prop("checked") == false){
                genre[1] = null;
            }
            actionSearch(champ);
        });

        /**
        * Event : au touche clavier
        */
        $('#search').on('keyup', function(e) {
            actionSearch(this);
        });

        function actionSearch(input) {
            $('.profile').remove();
            var data = [];
            data.push({
                'search': input.value,
                'range' : range,
                'genre' : genre
            });

            jsonString = JSON.stringify({data});
            // il faut declanché la recherche au bout de 4 caracteres 
            if (input.value.length >= 4) {

                search(jsonString);
            };
        }

        function search(jsonString) {
            $.ajax({
            type: "POST",
            url: "/api/search",
            data: "data="+jsonString,
            success: function(element) {
                 element.forEach(e => {
                        console.log(e.urlid);
                        $( ".gallery" ).append( '<div class="col-lg-3 col-md-4 col-6 profile"><a href="/product/'+e.urlid+'" class="d-block mb-4 h-100"><img class="img-fluid img-thumbnail" src="'+e.avatar+'" alt="'+e.pseudo+'"><span style="color:black" >'+e.pseudo+'-'+e.age+' ans -'+e.city+'</span>' );

                }) 
            }
        });
        }
        



    </script>
{% endif %}

{% if app.request.get('_route') == 'stats' %}
    <script src="{{ asset('assets/js/apexcharts.min.js') }}"></script>
<script>

    var options_age = {
        series: [{
            name: "Desktops",
            data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
        }],
        chart: {
            height: 350,
            type: 'line',
            zoom: {
            enabled: false
            }
        },
        dataLabels: {
            enabled: false
        },
        stroke: {
            curve: 'straight'
        },
        title: {
            text: 'Product Trends by Month',
            align: 'left'
        },
        grid: {
            row: {
            colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
            opacity: 0.5
            },
        },
        xaxis: {
            categories: ['19 ans', '21 ans', '22 ans', '23 ans', '24 ans', '25 ans', '26 ans', '27 ans', '28 ans'],
        }
        };

        var chart_age = new ApexCharts(document.querySelector("#age"), options_age);
        chart_age.render();




    var options = {
    series: [{
        name: 'TEAM A',
        type: 'column',
        data: [23, 11, 22, 27, 13, 22, 37, 21, 44, 22, 30]
    }, {
        name: 'TEAM B',
        type: 'area',
        data: [44, 55, 41, 67, 22, 43, 21, 41, 56, 27, 43]
    }, {
        name: 'TEAM C',
        type: 'line',
        data: [30, 25, 36, 30, 45, 35, 64, 52, 59, 36, 39]
    }],
    chart: {
        height: 350,
        type: 'line',
        stacked: false,
    },
    stroke: {
        width: [0, 2, 5],
        curve: 'smooth'
    },
    plotOptions: {
        bar: {
        columnWidth: '50%'
        }
    },
    
    fill: {
        opacity: [0.85, 0.25, 1],
        gradient: {
        inverseColors: false,
        shade: 'light',
        type: "vertical",
        opacityFrom: 0.85,
        opacityTo: 0.55,
        stops: [0, 100, 100, 100]
        }
    },
    labels: ['01/01/2003', '02/01/2003', '03/01/2003', '04/01/2003', '05/01/2003', '06/01/2003', '07/01/2003',
        '08/01/2003', '09/01/2003', '10/01/2003', '11/01/2003'
    ],
    markers: {
        size: 0
    },
    xaxis: {
        type: 'datetime'
    },
    yaxis: {
        title: {
        text: 'Points',
        },
        min: 0
    },
    tooltip: {
        shared: true,
        intersect: false,
        y: {
        formatter: function (y) {
            if (typeof y !== "undefined") {
            return y.toFixed(0) + " points";
            }
            return y;
    
        }
        }
    }
    };

    var chart = new ApexCharts(document.querySelector("#chart"), options);
    chart.render();

</script> 


{% endif %}

{% if app.request.get('_route') == 'user.worker' %}
    <script src="https://cdn.jsdelivr.net/npm/socket.io-client@2/dist/socket.io.js"></script>
    <script>


       


    
        let socket = io.connect('{{ app.environment == 'dev' ? 'localhost' : '' }}:3000', { query: {token: '{{ app.user != null ? app.user.jwtToken : '' }}'}});
        $('form').submit(function(e) {
            e.preventDefault(); // prevents page reloading
            socket.emit('notify', $('#m').val());
            $('#m').val('');
            return false;
        });

        $('#player').click(function(){
            if($(this).prop("checked") == true){
                console.log("Checkbox is checked.");
                socket.emit('player', 'activate');
                $('#log').append(' <span style="color:white"> rbtsv2@rbtsv2:~$ <cs style="color:green">player is activate</cs> </span><br>');

            }
            else if($(this).prop("checked") == false){
                console.log("Checkbox is unchecked.");
                socket.emit('player', 'desactivate');
                $('#log').append(' <span style="color:white">rbtsv2@rbtsv2:~$ <cs style="color:grey">player is desactivate </cs></span><br>');
            }
        });
  

        {# socket.on('result', data =>
        {

   
         
        });   #}
    </script>
{% endif %}


{% if app.request.get('_route') == 'payment' %}
    {# <script src="https://js.stripe.com/v3/"></script>
    <script src="{{ asset('js/stripe.js') }}"></script>  #}
{% endif %}

{% if app.request.get('_route') == 'search' %}
<script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
{% endif %}

{% endblock %}

templates/layout/header.html.twig
<head>
    <title>{% block title %}Social Engine | Web tools{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="Social Engine">
    <meta name="description" content="web tools">
    <meta name="author" content="RbtsV2">

    <link rel="shortcut icon" href="{{ asset('img/logo.png') }}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{{ asset('img/logo.png') }}">

    {% block stylesheets %}
     <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-4.css') }}">
     <link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">

     <link rel="stylesheet" href="{{ asset('assets/css/geoapis.css') }}">
     <link rel="stylesheet" href="{{ asset('assets/css/custom_maps.css') }}">

     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.3/dist/leaflet.css"/>
     <link rel="stylesheet" href="https://leaflet.github.io/Leaflet.markercluster/dist/MarkerCluster.css"/>

     <link rel="stylesheet" href="{{ asset('assets/css/dataTables.min.css') }}">
     <link rel="stylesheet" href="{{ asset('assets/css/apexcharts.css') }}">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
   


    <link href="https://rawgit.com/seiyria/bootstrap-slider/master/dist/css/bootstrap-slider.min.css" rel="stylesheet" type="text/css" />
    <script src="https://rawgit.com/seiyria/bootstrap-slider/master/dist/bootstrap-slider.min.js"></script>
    {% endblock %}
        
    {% if is_granted('ROLE_ADMIN') %}
        {# <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css">
        <link rel="stylesheet" href="{{ asset('css/admin.css') }}" /> #}
    {% else %}
    {% endif %}
</head>

templates/layout/navbar.html.twig
<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color:white; border-bottom:2px solid #cecbcb">
    <div class="container">

        <a class="navbar-brand" href="{{ path('home') }}">
            <img style="width:230px"src="{{ asset('assets/img/logo.png') }}" alt="logo">
            <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
            width="30pt" height="30pt" viewBox="0 0 1280.000000 853.000000"
            preserveAspectRatio="xMidYMid meet">

            <g transform="translate(0.000000,853.000000) scale(0.100000,-0.100000)"
            fill="#ff4081" stroke="none">
            <path d="M4315 7569 c-588 -325 -1103 -831 -1449 -1422 -71 -120 -201 -389
            -251 -517 -151 -385 -239 -798 -261 -1212 l-7 -138 -461 -2 -461 -3 0 -35 0
            -35 461 -3 461 -2 7 -143 c38 -818 323 -1578 833 -2218 128 -161 438 -473 584
            -588 213 -167 382 -279 609 -403 118 -64 129 -68 190 -68 l65 0 -145 73
            c-1114 561 -1878 1622 -2049 2847 -15 110 -40 404 -41 493 0 4 116 7 259 7
            l258 0 7 -132 c51 -974 512 -1844 1290 -2438 499 -381 1104 -606 1749 -652
            l177 -12 0 -93 0 -93 40 0 40 0 0 93 0 93 168 12 c459 33 830 132 1227 327
            336 166 590 347 858 613 373 369 641 800 801 1291 96 291 142 545 162 874 l6
            117 256 0 255 0 -6 -162 c-22 -582 -203 -1196 -508 -1714 -163 -278 -349 -516
            -593 -760 -305 -305 -569 -498 -951 -696 l-170 -87 61 -1 c55 0 73 6 160 51
            351 183 651 405 940 693 687 688 1069 1555 1120 2544 l7 132 458 0 459 0 0 40
            0 40 -459 0 -458 0 -7 113 c-35 585 -164 1077 -406 1552 -188 371 -389 651
            -680 949 -273 280 -522 472 -859 665 -115 65 -129 71 -180 70 -66 0 -72 5 104
            -90 924 -500 1609 -1387 1860 -2409 60 -246 105 -567 105 -757 l0 -93 -255 0
            -255 0 0 24 c0 55 -21 289 -36 391 -46 330 -156 680 -310 986 -454 908 -1303
            1551 -2299 1743 -151 29 -391 56 -499 56 l-75 0 -3 73 -3 72 -35 0 -35 0 -3
            -71 -3 -71 -140 -6 c-159 -8 -373 -37 -534 -73 -1232 -277 -2196 -1243 -2468
            -2474 -36 -161 -55 -299 -69 -487 l-12 -163 -257 0 -257 0 4 98 c46 902 364
            1688 955 2357 296 336 703 651 1087 844 45 23 82 43 82 46 0 3 -24 5 -53 5
            -46 0 -67 -8 -162 -61z m1825 -397 l0 -259 -123 -6 c-447 -23 -931 -183 -1312
            -434 -402 -266 -726 -632 -935 -1057 -162 -331 -242 -621 -272 -993 l-11 -143
            -259 0 -258 0 4 38 c3 20 8 87 11 147 26 494 212 1051 502 1499 414 639 1070
            1129 1787 1335 263 75 565 124 809 130 l57 1 0 -258z m426 233 c584 -70 1119
            -293 1603 -667 132 -103 400 -369 511 -508 414 -519 666 -1174 697 -1812 l6
            -138 -256 0 -255 0 -6 78 c-13 161 -37 341 -62 452 -115 517 -382 989 -771
            1360 -314 299 -697 519 -1114 639 -196 56 -475 101 -631 101 l-68 0 0 261 0
            262 113 -7 c61 -4 166 -14 233 -21z m-426 -770 l0 -225 -54 0 c-73 0 -267 -26
            -386 -51 -305 -66 -645 -231 -900 -436 -99 -80 -290 -277 -366 -379 -138 -183
            -249 -392 -322 -606 -64 -184 -95 -343 -118 -590 l-6 -68 -221 0 -222 0 6 118
            c35 622 312 1235 764 1687 338 338 773 584 1227 695 183 45 390 75 546 79 l52
            1 0 -225z m360 204 c290 -34 566 -117 845 -254 800 -393 1346 -1166 1450
            -2054 8 -69 15 -154 15 -188 l0 -63 -219 0 c-247 0 -231 -6 -231 85 0 88 -29
            270 -65 410 -192 747 -776 1343 -1522 1554 -134 38 -307 68 -447 77 l-106 7 0
            225 0 225 98 -7 c53 -4 135 -11 182 -17z m-360 -1603 l0 -603 -38 -7 c-65 -10
            -177 -73 -221 -122 -47 -54 -89 -134 -98 -186 l-6 -38 -607 0 -608 0 5 48 c27
            312 112 561 272 797 229 341 581 583 981 674 104 24 199 38 273 40 l47 1 0
            -604z m355 573 c209 -42 408 -126 595 -250 135 -89 334 -291 429 -432 156
            -236 249 -497 267 -754 l7 -93 -605 0 -606 0 -7 38 c-26 140 -172 283 -314
            307 l-38 6 -6 301 c-9 382 -9 753 0 842 l6 68 86 -6 c47 -4 131 -16 186 -27z
            m-355 -1379 l0 -150 -155 0 c-93 0 -155 4 -155 10 0 5 9 34 20 64 36 95 127
            179 233 211 23 8 45 14 50 14 4 1 7 -66 7 -149z m186 115 c28 -12 69 -39 91
            -59 40 -36 95 -127 107 -178 l6 -28 -155 0 -155 0 0 150 0 150 28 -6 c15 -3
            50 -16 78 -29z m-2832 -462 c40 -673 308 -1273 781 -1749 473 -475 1079 -748
            1753 -790 l112 -7 0 -257 0 -257 -77 4 c-774 38 -1432 301 -2005 800 -613 533
            -1023 1354 -1073 2148 -3 50 -8 120 -11 158 l-5 67 259 0 259 0 7 -117z m501
            25 c30 -409 143 -753 354 -1076 215 -328 509 -588 858 -761 264 -131 536 -204
            841 -226 l92 -7 0 -223 0 -222 -77 4 c-425 22 -838 141 -1191 344 -480 276
            -878 715 -1097 1209 -121 273 -204 595 -220 855 -3 55 -8 121 -11 148 l-5 47
            225 0 224 0 7 -92z m1785 40 c31 -150 147 -273 295 -313 l65 -18 0 -604 0
            -604 -62 6 c-440 43 -750 185 -1038 474 -131 131 -212 239 -293 391 -87 163
            -158 397 -172 564 -3 39 -8 90 -11 114 l-5 42 605 0 605 0 11 -52z m360 -109
            l0 -162 -36 6 c-126 21 -249 147 -270 276 l-7 41 157 0 156 0 0 -161z m385
            124 c-11 -63 -50 -138 -95 -183 -44 -44 -149 -100 -187 -100 -23 0 -23 1 -23
            160 l0 160 156 0 156 0 -7 -37z m1262 -65 c-15 -264 -126 -573 -290 -805 -78
            -110 -246 -282 -354 -361 -254 -186 -526 -287 -854 -316 l-67 -6 -7 97 c-4 53
            -4 325 0 604 l8 506 60 17 c33 9 79 28 102 42 89 52 175 172 191 264 3 19 7
            41 9 48 4 9 133 12 606 12 l602 0 -6 -102z m1020 -25 c-8 -169 -30 -315 -77
            -499 -49 -193 -93 -311 -190 -509 -251 -516 -670 -936 -1191 -1194 -312 -155
            -660 -251 -969 -267 -58 -3 -117 -7 -132 -9 l-28 -4 0 223 0 224 88 7 c229 17
            473 70 655 141 747 293 1266 945 1381 1735 9 59 16 131 16 162 0 30 3 69 6 86
            l7 31 220 0 220 0 -6 -127z m573 38 c0 -334 -100 -782 -255 -1146 -276 -644
            -773 -1194 -1393 -1540 -394 -220 -903 -369 -1327 -390 -60 -3 -127 -8 -147
            -11 l-38 -4 0 258 0 258 155 12 c318 25 596 94 880 217 568 247 1041 693 1318
            1243 181 359 264 669 293 1095 l6 97 254 0 254 0 0 -89z"/>
            </g>
            </svg>

        </a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
         
            <ul class="navbar-nav ml-auto">
                {% if app.user %}
                    {% set email = app.user.email | split('@') %}
                <li style="padding:10px"class="nav-item">
                     <a class="list-group-item" href="">
                                <i class="feather icon-log-out"></i> Se déconnecter
                    </a>
                </li>
                    {# <div class="dropdown">
                        <a href="#" class="text-white radial_progress dropdown-toggle dropdown-user-menu" style="width:40px;height: 40px;position:absolute;"  data-toggle="dropdown">
                            {% set percent = 0 %}
                            {% if app.user.subscription|length > 0 %}
                                {% if app.user.subscription[0].status == 'active' %}
                                    {% set percent = (app.user.credits / app.user.subscription[0].offer.credits) * 100 %}
                                {% elseif app.user.subscription[0].status == 'trialing'%}
                                    {% set percent = (app.user.credits / 20) * 100 %}
                                {% else %}
                                    {% set percent = (app.user.credits / app.user.credits) * 100 %}
                                {% endif %}
                            {% else %}
                                {% set percent = (app.user.credits / app.user.credits) * 100 %}
                            {% endif %}
                            <progress-ring progress="{{ percent }}" radius="20" stroke="2" background="#282d33">
                            </progress-ring>
                            <i class="feather icon-user" style="position:absolute; left: 12px;top: 12px; "></i>
                        </a>
                       
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item">{{ email[0] }} <span id="user_credits"> (<b>{{ app.user.credits|number_format(0, ',', ' ') }} credit{% if app.user.credits > 1 %}s{% endif %}</b>)</span></a>
                            <div class="dropdown-divider"></div>
                             {% if is_granted('ROLE_ADMIN') %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ path('admin.dashboard') }}">
                                    <i class="feather icon-command"></i> Administration
                                </a>
                             {% endif %}
                           
                        </div>
                   
                    </div> #}
             

                {% else %}
                    <li style="padding:10px"class="nav-item">
                        <a style="color:black" class="nav-link menu" href="{{ path('maps') }}">Maps</a>
                    </li>
                    <li style="padding:10px" class="nav-item">
                        <a style="color:black" class="nav-link menu" href="{{ path('search') }}">Recherche</a>
                    </li>
                    <li style="padding:10px" class="nav-item">
                        <a style="color:black" class="nav-link menu" href="{{ path('user.worker') }}">Booster son profil</a>
                    </li>
                    <li style="padding:10px" class="nav-item">
                        <a style="color:black" class="nav-link menu" href="{{ path('stats') }}">Statistiques</a>
                    </li>
                    <li style="padding:10px" class="nav-item menu">
                        <a style="border: dashed 2px #ff4081;padding:5px; color:grey; border-radius: 5px"class="nav-link" href="{{ path('login') }}">SE&nbsp;CONNECTER</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

</nav>

templates/layout/vertical_navbar.html.twig
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
            <a class="nav-link active" href="{{ path('maps') }}">
                <span data-feather="home"></span>
                Maps <span class="sr-only">(current)</span>
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ path('search') }}">
                <span data-feather="shopping-cart"></span>
                Search
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ path('stats') }}">
                <span data-feather="file"></span>
                Stats
            </a>
            </li>
        </ul>
    </div>
</nav>